services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      CONFIG_PATH: ${CONFIG_PATH:-settings/local/conf.yml}
      DJANGO_HOST: 0.0.0.0
      DJANGO_PORT: 8000
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-bookworm
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: yield_curves
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yield_curves"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0-bookworm
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
