# Generated by Django 5.2.1 on 2025-06-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yield_curves", "0003_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
