# Generated by Django 5.2.1 on 2025-06-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yield_curves', '0004_analysis_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='country',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='date',
        ),
    ]
