# Generated by Django 5.2.1 on 2025-06-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yield_curves", "0006_bondscatter_yieldcurve"),
    ]

    operations = [
        migrations.AddField(
            model_name="bond",
            name="is_green",
            field=models.BooleanField(default=False),
        ),
    ]
