# Generated by Django 5.2.1 on 2025-06-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yield_curves', '0008_bond_is_indexed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='is_deleted',
        ),
    ]
